Repository server-geeks/DSAHub, pull requests merged in 2022-10, with the labels that each got.

#2 Richest-customer-wealth
  leetcode/easy/richest-customer-wealth.cpp
Labels: hacktoberfest2022

#4 Peak index in a mountain array
  leetcode/medium/Peak Index in a Mountain Array.cpp
Labels: hacktoberfest, hacktoberfest2022

#7 Update README.md
  leetcode/medium/README.md
Labels: hacktoberfest, hacktoberfest2022

#12 Added New Question - Height Checker
  leetcode/easy/README.md
  leetcode/easy/height-checker.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#13 Added my question's solutions
  leetcode/easy/202happynumber.py
  leetcode/easy/README.md
  leetcode/hard/README.md
  leetcode/hard/poorpig.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#10 Print first n Fibonacci Numbers
  GeeksForGeeks/Print first n Fibonacci Numbers.cpp
  GeeksForGeeks/README.md
Labels: hacktoberfest, hacktoberfest-accepted

#15 Create Target Array
  leetcode/easy/README.md
  leetcode/easy/create-target-array.cpp
Labels: hacktoberfest, hacktoberfest2022

#20 Added medium question search in rotated sortedd array
  leetcode/medium/README.md
  leetcode/medium/search-in-rotated-sorted-array.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#23 Create SnakeWaterGun.py
  Miscellaneous/README.md
  Miscellaneous/SnakeWaterGun.py
Labels: hacktoberfest, hacktoberfest2022, changes-requested

#31 Added Leetcode hard solution
  leetcode/hard/Whildcard matching/README.md
  leetcode/hard/Whildcard matching/solution.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022
